### ISSUE TITLE
Request_redraw() call from another thread doesn’t produce RedrawRequested event.

### ISSUE THREAD

**Issue by VincentFTS** [rust-windowing/winit#1763]
On MacOS, when Window::request_redraw() is called from another thread, Event::RedrawRequested is not emitted until another event is.
To reproduce this, just launch request_redraw_threaded example.

**Comment by VincentFTS** [comment]
FYI : not reproduced with X11, but reproduced with web-sys.

**Comment by kchibisov** [comment]
I think some backends don't wake up for whatever reason, and it was fixed like recently for X11.

I know that it wake ups on Wayland, so I'll save time testing.

**Comment by VincentFTS** [comment]
I hope this whatever reason is whatever easy to fix !!

**Comment by mr1sunshine** [comment]
I can confirm that this is still an issue on the current `master`. I can work it out with having `Poll` control flow, but it consumes a lot of resources unfortunately. I'm just wondering if there are any estimations on it?

**Comment by ArturKovacs** [comment]
Resolved by #1812
