### ISSUE TITLE
Let `Window::inner_size()` return `None` if the Window isn't "ready" yet

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#2863]
I've heard this come up many times before, but when using Winit to render stuff, users often have to check for the window size not to be zero.

I've encountered this before in X11, but I don't know the story behind this on other backends. For Wasm, it's easy to hit this problem at application startup, where the canvas isn't even inserted yet into the DOM, where it makes perfect sense to return `None` in `Window::inner_size()`. See https://github.com/rust-windowing/winit/pull/2859#discussion_r1222452529 which spawned this issue.

**Comment by kchibisov** [comment]
This is more general issue of async window startup, we have similar problem on Wayland, which is solved right now by dispatching event loop and waiting for the events to complete.

@rib do you happen to remember what the conclusion for stuff like that was? I think we need a way for window to be created async.

My initial idea would be to have normal constructor for that which will return not a window, but `WindowId`, as it'll reserve the slot for window in the backends internal map with unique ids, so the user will have a target for events and a place in the hash map, and the actual window will be received as part of some event so they insert into vacant slot in the map/whatever they use?

**Comment by mcclure** [comment]
Just to note, I filed [a dupe of this bug](https://github.com/rust-windowing/winit/issues/2967) in 2023, and I am still experiencing the problem (in the form of [my program often being unable to run in wasm if I don't include protective code for the nonsense case of a 0,0 window](https://data.runhello.com/j/wgpu/special/stagingbelt/4/)) as of 0.30.4.
