### ISSUE TITLE
All of the examples are missing

### ISSUE THREAD

**Issue by aloucks** [rust-windowing/winit#3512]
As stated all of the examples are gone. There's one mega example, but it's less helpful when trying to figure out a specific concept.

**Comment by madsmtm** [comment]
Yeah, we merged them in https://github.com/rust-windowing/winit/pull/3447, since we thought it important to give a fuller example of what a real application might look like. What specific concept are you struggling with?

**Comment by aloucks** [comment]
It's more that they offered an index for features and how to solve specific problems. Now the end users have to go through that whole mega example to find the thing they are looking for. Reading and understanding 1000 lines of unfamiliar code is much more involved than 50-100 lines of highly a specific example. Having an index of small examples is much easier from a user perspective.

**Comment by kchibisov** [comment]
I still don't understand, you go and read methods on the `Window` itself, because that's what most of them did and what got removed. Examples on how to use completely different things like pump_events, child_windows are still there.

Like if the struggle is with search within a file I'm not really sure how to help with that. In general really small examples should go into the method/event docs, since that's where they should be.

The example won't change anyway, since it's the only way to have actually useful bug reports, since you can test with that example pretty much everything relatively easy and compare.

**Comment by madsmtm** [comment]
I've reopened this to allow further discussion of this (CC https://github.com/rust-windowing/winit/pull/4136).

**Comment by kchibisov** [comment]
my stance is the same, if example shows a specific pattern of usage of winit in its own (run_on_demand, some drawing pattern) it deserves its own example, otherwise it should go to the documentation method.

Maintaining hundreds of examples at this state is not a good option. One could move e.g. platform specific examples into its own example, like `windows_window.rs`, etc, so platform specific patterns are shown in isolation, but that's about it.
